### ISSUE TITLE
Cannot load system from NVME drive

### ISSUE THREAD

**Issue by mlevkov** [abdyfranco/next-loader#1]
Hi, 

I've tried to load the os from the freshly installed NVME 970 drive. Does it load some kind of driver from your tool or something else? I've tried install/reinstall multiple times. I load OS from USB drive, then format the NMVE 970EVO, then reboot with Next Loader installed. During the High Sierra OS installation, the installation goes into reboot at about 2 minute mark remaining and circle of efforts repeats again (reboot, reinstall, auto-reboot). Should I be expecting some kind of other behavior with your tool installed as boot manager?

**Comment by abdyfranco** [comment]
This is caused because a driver crashes when loading Next Loader, this has been previously reported by some other users as well. I'm working on identifying which driver causes the boot loader to crash.
I'll publish more information about it as soon as I find the cause.

**Comment by mlevkov** [comment]
Will look out for the solution. I had it installed on separate USB drive.

**Comment by abdyfranco** [comment]
Next Loader must be installed on an AHCI drive to be able to boot an NVMe drive.
