### ISSUE TITLE
Need Help understanding how to get windows on my mac

### ISSUE THREAD

**Issue by TimFreitas** [abdyfranco/next-loader#15]
I have the UEFI Boot Manager set up and working along with the Boot Manager.  I like the concept but don't understand what to do now.  I am not a programer.  There is no manual to read on how to get windows on my mac.  Am I suppose to put windows on the UEFI Boot Manger?  Or am I suppose to load in on a NTFS formated hard drive and load it on my Mac pro?  I can't find any information on this site on how to do this.  I'm lost about the next step.

Please help
Tim

**Comment by abdyfranco** [comment]
You can install Windows without the need of Next Loader using Bootcamp, but if you want to install Next Loader, you need to install it on a HFS+ formatted drive, then you install windows on a NTFS formatted partition.
