### ISSUE TITLE
Pantalla en Blanco en Mac Pro con tarjeta compatible EFI (shaphire 7950)

### ISSUE THREAD

**Issue by Alfuman** [abdyfranco/next-loader#16]
Hola, he intentado usar next loader en un Mac Pro 5.1, con una tarjeta gráfica Shapphire 7950, que supuestamente es compatible con el bootloader, he realzado la instalación en un pendrive USB, conectado a los puertos USB 2.0 delanteros del Mac, se ha realzado todo correctamente. He reiniciado el ordenador y me ha salido la pantalla donde se pueden elejir los HD para inciar el SO, se ha iniciado sin tocar nada, pero al reiniciar el equipo o arrancar de cero ya no puedo ver la pantalla de next.loader, incluso haciendo el proceso de nuevo, después de oír las chimes, se ve como lee el pendrive, pero la pantalla se queda en blanco y luego inicia con un SO de los que tengo instalados, High Sierra o Mojave, también tengo un windows 10 que no me aparece por ningún sitio y por eso la utilización de un bootloader. También tengo el problema de que el gestor de arranque de Mac no lee los HD donde tengo instalados los SO, aparece la flecha pero los HD no, y eso que lo he dejado un buen rato. O se será por que tengo un SSD instalado en una tarjeta sonnett pro y uno de los SO esta instalado en ese SSD, pero antes si funcionaba el gestor de arranque. Igual es un problema del ordenador.
También comentar que tengo una llave iLok para programas que uso, pero al inciar el SO me sale una ventana que comenta que tengo que desconectar la llave y volverla a conectar ya que no la puedo utilizar con dos SO diferentes, esto también me pasa cuando consigo entrar a windows 10 y vuelvo a Mac, o sea que es una cuestión de la llave, pero me parece raro que estando en MAc me aparezca el cartel.
Saludos.

**Comment by Alfuman** [comment]
Hola, parece que el problema viene por el ssd instalado en la tarjeta de expansión sonnett tempo, no s peor que pero con los nuevos SO, no funciona el gestor de arranque. S tengo una partición con un SO, el gestor de arranque no muestra los sistemas booteables, al borrar la partición vuelve a funcionar sin problemas...

**Comment by abdyfranco** [comment]
La tarjeta Sonnet Tempo suele dar diversos problemas, no solo con Next Loader, si no también inclusive con macOS y Windows. Mi solución fue instalar Next Loader en una partición en el SSD instalado en el Sonnet Tempo, si se instala en un disco conectado a alguno de los puertos nativos del Mac Pro, La pantalla se queda en blanco.
