### ISSUE TITLE
Freeze on Raid 0

### ISSUE THREAD

**Issue by czterystatrzy** [abdyfranco/next-loader#17]
I’ve bundled together 2 HDDs / 2 TB HGST into raid 0 under Mac OS high Sierra. Now the nextloader freezes if they are connected to the SATA controller and doesn’t go to the boot menu

**Comment by abdyfranco** [comment]
Next Loader does not support boot from software RAID. Only from FusionDrive or hardware RAID (at the moment, tested only on a Mac Pro, not sure about hardware RAID on a Xserve)
