### ISSUE TITLE
Manually change which EFI boots are available in the boot menu?

### ISSUE THREAD

**Issue by phishfi** [abdyfranco/next-loader#19]
Is there any setting/config where I can manually remove menu options from showing up in the boot menu? Right now, I'm stuck with 2 references to MacOS and 2 references to Windows 10. I'd prefer to limit them down to just one each, and then eventually add a Linux image and menu option.

Also, I'd prefer to hide a Windows recovery and Mac recovery option within a menu option, so I can click a button and pick which recovery loader to load.

**Comment by kumowoon1025** [comment]
Hmm.. Idk if this might cause trouble in the future if you can't boot from your main partitions since you will have to reverse the procedure,

`sudo bless --unbless /Volumes/UnwantedBootPartition`

try this though.

**Comment by abdyfranco** [comment]
You can hide an unwanted entry on Next Loader, by selecting the entry and pressing the delete key. You can access hidden entries on the Options menu. This behavior is inherited from rEFInd, so you can check their documentation for more information. https://www.rodsbooks.com/refind/configfile.html

You can also add custom entries using stanzas, you can check the file "stanzas.conf", includes some examples that you can modify to add a custom entry.

**Comment by phishfi** [comment]
Awesome, thank you for the explanation!
