### ISSUE TITLE
Fails to load on MP3,1

### ISSUE THREAD

**Issue by lyons88** [abdyfranco/next-loader#2]
The loader.efi silently fails to load on my Mac Pro3,1. If I boot to a shell and side load the loader.efi, here is the error I get:

ASSERT_EFI_ERROR (Status + Not Found)
ASSERT [UsbKbDxe] /root/next-loader/src/edk2/UDK2018/MyWorkSpace/MdeModule/Library/UefiHiiServicesLib/UefiHiiServices.c(100) : !EFI_ERROR (Status)

**Comment by lyons88** [comment]
abdy?

**Comment by abdyfranco** [comment]
Fixed on #1bc8d17
