### ISSUE TITLE
How to install themes?

### ISSUE THREAD

**Issue by CharlieT12321** [abdyfranco/next-loader#20]
Hi. Apologies if this is present in your documentation already, but I couldn't find how to install the themes available on your site. I've successfully installed the Loader, but don't know how to apply themes. Thanks

**Comment by abdyfranco** [comment]
All the themes has a "theme.conf" file inside, you only need to add "include themes/theme_name/theme.conf" at the end of the "loader.conf" file, replacing "theme_name" for the folder name of the theme you want to install.
