### ISSUE TITLE
Boot Picker freezes when choosing More Options

### ISSUE THREAD

**Issue by misanthrophy** [abdyfranco/next-loader#3]
Hi,

I am using a Mac Pro 4.1 flashed to 5.1 and running macOS 10.13.6

On my internal PCIe card I have installed a SM951 NVMe SSD.
I used the method from [foxfoobar on MacRumors](https://forums.macrumors.com/threads/boot-osx-on-a-nvme-card.1967790/) to boot from the SSD with an external USB drive.
I now made a new partition on the same USB drive and followed the instructions. 
When I reboot my Mac I see the drive "More Options", but as soon as I choose it, it freezes and all I can do is power cycle my Mac. 

1. Do I need a separate USB drive next to the NVMeBoot USB drive?
2. Is it possible to only use next-loader without the NVMeBoot USB drive, as it supports NVMe drives natively? 

Thanks in advance for your help!

**Comment by abdyfranco** [comment]
Thank you for reporting the bug, it was already fixed in #f8d7898
